sudo: false
language: php
php:
  - 5.5
  - 5.6
  - 7.0
before_install:
  ## Disable xdebug
  - phpenv config-rm xdebug.ini
  ## Update Composer
  - composer self-update
  ## Install latest version of node
  - nvm install node
install:
  ## Install Composer dependencies
  - composer install --no-interaction --prefer-dist
  ## Clone libraries
  - hg clone https://bitbucket.org/izi/polib app/libraries/polib -u 1.0.7
  - hg clone https://hg.mozilla.org/l10n/silme app/libraries/silme -u silme-0.8.0
  ## Copy config to avoid warning
  - cp app/config/config.ini-dist app/config/config.ini
  ## Install ESLint
  - npm install -g eslint
script:
  - vendor/atoum/atoum/bin/atoum -d tests/units/ --use-light-report
  - php tests/functional/api.php
  - php tests/functional/scripts.php
  - php tests/integrity/source_integrity.php
  - vendor/bin/php-cs-fixer --diff --dry-run -v fix
  - eslint web/assets/js
notifications:
  irc:
    channels:
      - "irc.mozilla.org#l10n-tools"
    on_success: always
    on_failure: always
    use_notice: true
    template:
      - "%{repository} ; %{commit} (%{author}) : %{message} "
      - "Build details: %{build_url} ; changes: %{compare_url}"
matrix:
  fast_finish: true
